import { Product } from '@/types';

// All images: single product on white/near-white bg, square crop, consistent size
export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-sk-01', code: 'SK-01', name: 'Glow Cream',
    description: 'Brightening face cream with Vitamin C. Evens skin tone and adds radiance in 2 weeks. Lightweight, non-greasy formula suitable for all skin types.',
    price: 25000, category: 'BASKETS', stock: 50,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000457/glow_cream_jm28ae.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-sk-02', code: 'SK-02', name: 'Clear Serum',
    description: 'Lightweight serum for acne-prone skin. Unclogs pores, reduces blemishes, and balances oil production without stripping moisture.',
    price: 35000, category: 'BASKETS', stock: 40,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000458/fade_cream_pky9lp.png',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-sk-03', code: 'SK-03', name: 'Fade Cream',
    description: 'Dark spot correcting cream with kojic acid and niacinamide. Visibly fades marks and hyperpigmentation within 4 weeks of use.',
    price: 30000, category: 'BASKETS', stock: 45,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000458/fade_cream_pky9lp.png',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-sk-04', code: 'SK-04', name: 'Day Shield SPF50',
    description: 'Moisturising sunscreen with SPF 50 PA+++. Protects against UVA/UVB damage while keeping skin hydrated and matte all day.',
    price: 28000, category: 'BASKETS', stock: 35,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000457/day_shield_pli9sz.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-bd-01', code: 'BD-01', name: 'Cocoa Butter',
    description: 'Rich body butter with raw cocoa and shea. Deep moisture that lasts 24 hours. Non-greasy finish for all skin types.',
    price: 22000, category: 'BODY', stock: 60,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000458/cocoa_butter_r0mlti.png',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-bd-02', code: 'BD-02', name: 'Rose Shower Gel',
    description: 'Luxurious shower gel with rose extract and almond oil. Gentle lather that cleanses without stripping natural oils.',
    price: 18000, category: 'BODY', stock: 55,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000459/shower_gel_qhiwvk.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-bd-03', code: 'BD-03', name: 'Coffee Scrub',
    description: 'Exfoliating body scrub with ground coffee and raw sugar. Reveals glowing skin and boosts circulation.',
    price: 20000, category: 'BODY', stock: 40,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000457/body_scrub_xb6lla.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-bd-04', code: 'BD-04', name: 'Glow Oil',
    description: 'Shimmer body oil with argan and jojoba. Leaves skin silky, luminous, and deeply nourished. No greasy residue.',
    price: 32000, category: 'BODY', stock: 30,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000457/glow_oil_evagem.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-fr-01', code: 'FR-01', name: 'Bloom EDP',
    description: 'Floral and fresh eau de parfum. Opens with jasmine and rose, settles into warm sandalwood and musk. Up to 8 hours wear.',
    price: 65000, category: 'SHOES', stock: 25,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000459/bloom_j5bvtx.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-fr-02', code: 'FR-02', name: 'Velvet EDP',
    description: 'Warm oriental SHOES for evenings. Rich blend of vanilla, amber, and white musk. Sensual, bold, long-lasting.',
    price: 70000, category: 'SHOES', stock: 20,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000457/bloom_i3p0gk.avif',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-fr-03', code: 'FR-03', name: 'Citrus Mist',
    description: 'Light refreshing body mist with lemon, bergamot, and green tea. Perfect for everyday freshness.',
    price: 25000, category: 'SHOES', stock: 45,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000456/citrus_mist_e0t7le.avif',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-lp-01', code: 'LP-01', name: 'Rose CRAFT Butter',
    description: 'Moisturising CRAFT butter with rose extract and vitamin E. Softens, plumps, and protects CRAFTs all day.',
    price: 12000, category: 'CRAFT', stock: 80,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000459/bloom_j5bvtx.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-lp-02', code: 'LP-02', name: 'Honey Balm',
    description: 'Healing CRAFT balm with raw honey and beeswax. Repairs severely chapped CRAFTs overnight.',
    price: 10000, category: 'CRAFT', stock: 90,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000456/honey_balm_rh0uch.avif',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-lp-03', code: 'LP-03', name: 'Berry Tint Oil',
    description: 'Sheer tinted CRAFT oil in deep berry. Hydrates and adds a natural flush of colour. Never sticky.',
    price: 15000, category: 'CRAFT', stock: 70,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000458/berry_tint_uf85yd.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-hr-01', code: 'HR-01', name: 'Castor Oil',
    description: '100% pure cold-pressed castor oil. Promotes HATS growth, strengthens roots, and restores scalp health.',
    price: 18000, category: 'HATS', stock: 50,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000456/castor_oil_etwkjy.jpg',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-hr-02', code: 'HR-02', name: 'Mango HATS Butter',
    description: 'Rich HATS butter with mango and avocado oil. Defines curls, eliminates frizz, adds incredible shine.',
    price: 24000, category: 'HATS', stock: 35,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000456/HATS_butter_g8ti5d.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-hr-03', code: 'HR-03', name: 'Scalp Oil',
    description: 'Tea tree and peppermint scalp treatment. Reduces dandruff, soothes itching, promotes healthy HATS growth.',
    price: 20000, category: 'HATS', stock: 40,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000458/scalp_oil_wv9gjj.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-ac-01', code: 'AC-01', name: 'Rose Quartz Roller',
    description: 'Genuine rose quartz facial roller. Reduces puffiness, boosts circulation, and lifts the face with regular use.',
    price: 35000, category: 'ACCESSORIES', stock: 20,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000456/face_roller_lesjeg.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-ac-02', code: 'AC-02', name: 'Lash Serum',
    description: 'Peptide-rich lash growth serum with biotin. Lengthens and thickens lashes visibly in 4–6 weeks.',
    price: 45000, category: 'ACCESSORIES', stock: 25,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000456/lash_serum_dg0xqg.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-ac-03', code: 'AC-03', name: 'Gua Sha Stone',
    description: 'Genuine green jade gua sha for facial sculpting. Defines jawline and boosts lymphatic drainage.',
    price: 28000, category: 'ACCESSORIES', stock: 3,
    image_url: 'https://res.cloudinary.com/dpl464cjn/image/upload/v1774000459/bloom_j5bvtx.webp',
    is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];

export const DEMO_ORDERS = [
  {
    id: 'demo-ord-01', order_number: 'RBS-241201-001',
    customer_name: 'Aisha Nakato', customer_phone: '0701234567', customer_email: 'aisha@example.com',
    delivery_address: 'Ntinda, Kampala', subtotal: 55000, delivery_fee: 5000, total: 60000,
    payment_method: 'MTN', payment_status: 'PAID', order_status: 'DELIVERED',
    marz_transaction_id: null, created_at: new Date(Date.now() - 86400000 * 2).toISOString(), updated_at: new Date().toISOString(),
    order_items: [
      { id: 'oi-1', order_id: 'demo-ord-01', product_id: 'demo-sk-01', product_name: 'Glow Cream', product_code: 'SK-01', quantity: 1, unit_price: 25000, subtotal: 25000 },
      { id: 'oi-2', order_id: 'demo-ord-01', product_id: 'demo-bd-01', product_name: 'Cocoa Butter', product_code: 'BD-01', quantity: 1, unit_price: 22000, subtotal: 22000 },
    ],
  },
  {
    id: 'demo-ord-02', order_number: 'RBS-241202-002',
    customer_name: 'Grace Tumwine', customer_phone: '0782345678', customer_email: '',
    delivery_address: 'Bukoto, Kampala', subtotal: 70000, delivery_fee: 5000, total: 75000,
    payment_method: 'AIRTEL', payment_status: 'PAID', order_status: 'CONFIRMED',
    marz_transaction_id: null, created_at: new Date(Date.now() - 86400000).toISOString(), updated_at: new Date().toISOString(),
    order_items: [
      { id: 'oi-4', order_id: 'demo-ord-02', product_id: 'demo-fr-01', product_name: 'Bloom EDP', product_code: 'FR-01', quantity: 1, unit_price: 65000, subtotal: 65000 },
    ],
  },
  {
    id: 'demo-ord-03', order_number: 'RBS-241203-003',
    customer_name: 'Sharon Atim', customer_phone: '0753456789', customer_email: 'sharon@gmail.com',
    delivery_address: 'Muyenga, Kampala', subtotal: 63000, delivery_fee: 5000, total: 68000,
    payment_method: 'MTN', payment_status: 'PENDING', order_status: 'PENDING',
    marz_transaction_id: null, created_at: new Date(Date.now() - 3600000 * 3).toISOString(), updated_at: new Date().toISOString(),
    order_items: [
      { id: 'oi-6', order_id: 'demo-ord-03', product_id: 'demo-sk-02', product_name: 'Clear Serum', product_code: 'SK-02', quantity: 1, unit_price: 35000, subtotal: 35000 },
    ],
  },
  {
    id: 'demo-ord-04', order_number: 'RBS-241203-004',
    customer_name: 'Prossy Nalwoga', customer_phone: '0701234567', customer_email: '',
    delivery_address: 'Nansana, Wakiso', subtotal: 53000, delivery_fee: 8000, total: 61000,
    payment_method: 'CARD', payment_status: 'PAID', order_status: 'PROCESSING',
    marz_transaction_id: 'TXN-CARD-00123', created_at: new Date(Date.now() - 1800000).toISOString(), updated_at: new Date().toISOString(),
    order_items: [
      { id: 'oi-9', order_id: 'demo-ord-04', product_id: 'demo-bd-04', product_name: 'Glow Oil', product_code: 'BD-04', quantity: 1, unit_price: 32000, subtotal: 32000 },
    ],
  },
];
